### PR TITLE
#191 Add support for configuring auth schemes

### LINKED ISSUE #191: Authentication schemes supporting in extension methods
Hello. 
I am using this SDK to add MVC and WebApi authentication via Okta but extension methods (AddOktaMvc and AddOktaWebApi) from this SDK does not provide possibility to pass authentication schemes like standard microsoft extension methods (AddOpenIdConnect, AddJwtBearer). It is very useful to have this opportunity when you want to use multiple authentication schemes from multiple OKTA authorization servers.
Could you add authentication schemes for the extension methods?

### PR DESCRIPTION
**Pull request by Tankatronic**
## Summary

Adds additional overloads for OktaAuthenticationOptionsExtensions to specify an authentication scheme.

Fixes #191 

## Type of PR

- [ ] Bug Fix (non-breaking fixes to existing functionality)
- [x] New Feature (non-breaking changes that add new functionality)
- [ ] Documentation update
- [ ] Test Updates
- [ ] Other (Please describe the type)

## Test Information

- [x] My PR required test updates 

.NET Version:
Os Version:

## Signoff
- [x] I have submitted a CLA for this PR
- [x] Each commit message explains what the commit does
- [x] I have updated documentation to explain what my PR does
- [x] My code is covered by tests if required
- [x] I checked StyleCop warnings on my code

### CODE REVIEW

**Comment by laura-rodriguez** [comment]
Hi @Tankatronic,

Thank you so much for your contribution ⭐ !  
I'm gonna create an internal ticket to review this PR to be prioritized by the team.

I can see you checked that you submitted the CLA, would you mind sharing your name so we can identify the CLA in our records? Also, are there any tests that are already covering this new functionality or should we add new ones?

**Comment by laura-rodriguez** [comment]
Internal Ref: OKTA-491167

**Comment by Tankatronic** [comment]
Hello! Yes my name is Justin Loveless. I did not create new tests, the
existing tests should cover the existing methods that I modified but more
will need to be added to test custom auth schemes.

Will there be a pre-release version of this package available while it is
under review?

**Comment by laura-rodriguez** [comment]
Thank you, Justin! I confirm we received your CLA.

Would you mind adding new tests to verify that we correctly set the custom scheme?

Re: pre-release - We generally don't do that. Once this is approved and merged, we'll ship a new version.

**Comment by Tankatronic** [comment]
Alright, tests are added for both Mvc and WebApi integration projects. I can remove the changes I added for appsettings.json files..just much easier for me for testing to use that. I injected appsettings first so any environment variables will override the values in appsettings.json.

**Comment by laura-rodriguez** [comment]
Superseded by #205

**Pull request closed without merging**
